/**
 * VRP Report Generator.
 *
 * Takes a confirmed, minimized, analyzed crash and produces a report shaped
 * for Google's Android Vulnerability Rewards Program (VRP).
 *
 * IMPORTANT: Fields marked REQUIRES HUMAN VERIFICATION / REQUIRES HUMAN
 * ASSESSMENT are intentionally left blank. Google's VRP quality guidelines
 * require a researcher-verified impact statement — an AI-generated one will get
 * the report flagged. AI output is a triage aid, never a submission.
 */

export function generateVRPReport(crash, analysis) {
  const component = analysis.component || crash.component || "Unknown";
  const vulnerabilityType = analysis.vulnerability_type || analysis.type || "Memory Corruption";
  const severity = analysis.severity || "high";
  const target = crash.target || "fuzzer_target";

  return {
    title: `${vulnerabilityType} in ${component} (${severity})`,

    description: analysis.root_cause_hypothesis || crash.cause || "No root-cause hypothesis available.",

    reproduction: {
      build_fingerprint: crash.build_fingerprint || "REQUIRES HUMAN VERIFICATION",
      device: crash.device || "REQUIRES HUMAN VERIFICATION",
      steps: [
        `1. Flash a userdebug build matching fingerprint: ${crash.build_fingerprint || "<fingerprint>"}`,
        `2. Push fuzzer binary: adb push ${target} /data/fuzz/arm64/${target}/`,
        `3. Push reproducer input: adb push ${crash.reproducer_path || "<minimized_input>"} /data/fuzz/reproducer.bin`,
        `4. Run: adb shell /data/fuzz/arm64/${target}/${target} /data/fuzz/reproducer.bin`,
        `5. Observe crash at: ${crash.fault_address || "<fault address>"} in ${crash.process || "<process>"}`,
      ],
    },

    evidence: {
      asanReport: crash.raw_log || crash.asan_report || null,
      tombstone: crash.tombstone_path || null,
      backtraceHash: crash.crash_id,
      reproducerInput: crash.reproducer_path || null, // attach this file
      supportingFrames: analysis.supporting_frames || [],
      referenceIds: analysis.reference_ids || [],
      missingEvidence: analysis.missing_evidence || [],
    },

    impact: {
      // Human must fill these in — never let AI auto-fill.
      severity,
      component,
      vulnerabilityClass: vulnerabilityType,
      confidence: analysis.confidence ?? null,
      affectedVersions: "REQUIRES HUMAN VERIFICATION",
      securityImpact: "REQUIRES HUMAN ASSESSMENT",
    },

    aiAnalysisNote: `
      This analysis was generated by Gemini ${analysis.model_version || analysis.modelVersion || "unknown"} as a
      triage aid. All fields marked REQUIRES HUMAN VERIFICATION must be confirmed
      before submission. AI-generated content should not be submitted verbatim
      to the VRP.
    `,
  };
}
